use std::mem::{align_of, offset_of, size_of};
use swiftflow_core::node::SFNode;

#[test]
fn sfnode_matches_the_c_header() {
    assert_eq!(size_of::<SFNode>(), 304, "struct size");
    assert_eq!(align_of::<SFNode>(), 8, "struct alignment");

    let expected: &[(&str, usize)] = &[
        ("node_id", 0),
        ("kind", 4),
        ("frame", 8),
        ("padding", 24),
        ("sizing_x", 40),
        ("sizing_y", 44),
        ("scale", 48),
        ("offset_x", 56),
        ("offset_y", 60),
        ("fill", 64),
        ("border", 80),
        ("corner_radius", 112),
        ("blur_radius", 116),
        ("specular", 120),
        ("clip_content", 124),
        ("edge_effect_height", 128),
        ("shadow_radius", 132),
        ("shadow_opacity", 136),
        ("no_merge", 140),
        ("progressive_blur", 144),
        ("progressive_start", 148),
        ("glass_refraction", 152),
        ("glass_interactive", 156),
        ("text", 160),
        ("text_len", 168),
        ("font_size", 176),
        ("font_weight", 180),
        ("font_family", 184),
        ("content_blur", 188),
        ("line_limit", 192),
        ("text_align", 196),
        ("color", 200),
        ("image_id", 216),
        ("image_content_mode", 220),
        ("axis", 224),
        ("alignment", 228),
        ("vertical_alignment", 232),
        ("main_axis_alignment", 236),
        ("spacing", 240),
        ("children", 248),
        ("children_len", 256),
        ("min_length", 264),
        ("fixed_width", 268),
        ("fixed_height", 272),
        ("scroll_id", 276),
        ("content_offset_x", 280),
        ("content_offset_y", 284),
        ("content_width", 288),
        ("content_height", 292),
        ("weight", 296),
    ];

    let actual: &[(&str, usize)] = &[
        ("node_id", offset_of!(SFNode, node_id)),
        ("kind", offset_of!(SFNode, kind)),
        ("frame", offset_of!(SFNode, frame)),
        ("padding", offset_of!(SFNode, padding)),
        ("sizing_x", offset_of!(SFNode, sizing_x)),
        ("sizing_y", offset_of!(SFNode, sizing_y)),
        ("scale", offset_of!(SFNode, scale)),
        ("offset_x", offset_of!(SFNode, offset_x)),
        ("offset_y", offset_of!(SFNode, offset_y)),
        ("fill", offset_of!(SFNode, fill)),
        ("border", offset_of!(SFNode, border)),
        ("corner_radius", offset_of!(SFNode, corner_radius)),
        ("blur_radius", offset_of!(SFNode, blur_radius)),
        ("specular", offset_of!(SFNode, specular)),
        ("clip_content", offset_of!(SFNode, clip_content)),
        ("edge_effect_height", offset_of!(SFNode, edge_effect_height)),
        ("shadow_radius", offset_of!(SFNode, shadow_radius)),
        ("shadow_opacity", offset_of!(SFNode, shadow_opacity)),
        ("no_merge", offset_of!(SFNode, no_merge)),
        ("progressive_blur", offset_of!(SFNode, progressive_blur)),
        ("progressive_start", offset_of!(SFNode, progressive_start)),
        ("glass_refraction", offset_of!(SFNode, glass_refraction)),
        ("glass_interactive", offset_of!(SFNode, glass_interactive)),
        ("text", offset_of!(SFNode, text)),
        ("text_len", offset_of!(SFNode, text_len)),
        ("font_size", offset_of!(SFNode, font_size)),
        ("font_weight", offset_of!(SFNode, font_weight)),
        ("font_family", offset_of!(SFNode, font_family)),
        ("content_blur", offset_of!(SFNode, content_blur)),
        ("line_limit", offset_of!(SFNode, line_limit)),
        ("text_align", offset_of!(SFNode, text_align)),
        ("color", offset_of!(SFNode, color)),
        ("image_id", offset_of!(SFNode, image_id)),
        ("image_content_mode", offset_of!(SFNode, image_content_mode)),
        ("axis", offset_of!(SFNode, axis)),
        ("alignment", offset_of!(SFNode, alignment)),
        ("vertical_alignment", offset_of!(SFNode, vertical_alignment)),
        ("main_axis_alignment", offset_of!(SFNode, main_axis_alignment)),
        ("spacing", offset_of!(SFNode, spacing)),
        ("children", offset_of!(SFNode, children)),
        ("children_len", offset_of!(SFNode, children_len)),
        ("min_length", offset_of!(SFNode, min_length)),
        ("fixed_width", offset_of!(SFNode, fixed_width)),
        ("fixed_height", offset_of!(SFNode, fixed_height)),
        ("scroll_id", offset_of!(SFNode, scroll_id)),
        ("content_offset_x", offset_of!(SFNode, content_offset_x)),
        ("content_offset_y", offset_of!(SFNode, content_offset_y)),
        ("content_width", offset_of!(SFNode, content_width)),
        ("content_height", offset_of!(SFNode, content_height)),
        ("weight", offset_of!(SFNode, weight)),
    ];

    assert_eq!(actual, expected);
}

#[test]
fn scroll_ffi_structs_match_the_c_header() {
    assert_eq!(size_of::<swiftflow_core::ffi::SFScrollMetrics>(), 16);
    assert_eq!(size_of::<swiftflow_core::ffi::SFScrollHit>(), 8);
}
