#!/usr/bin/env python3
"""Generate Sources/SwiftFlowCore/Views/PhosphorIcons.swift.

Reads the vendored name -> codepoint table beside the fonts, so this
runs offline and its input is diffable. To take a new Phosphor release,
run tools/fetch-phosphor.sh first — that refreshes both the TTFs and the
table — then run this.

    python3 tools/generate-icons.py

Stdlib only, on purpose: a code generator that needs its own install
step is a code generator nobody runs.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLE = ROOT / "rust/swiftflow_core/fonts/phosphor/icons.tsv"
OUT = ROOT / "Sources/SwiftFlowCore/Views/PhosphorIcons.swift"

# Swift's reserved words. Only `repeat` collides today, but the set is
# cheap to carry and a new icon called `class` or `default` would
# otherwise generate a file that doesn't compile.
SWIFT_KEYWORDS = set(
    """associatedtype class deinit enum extension fileprivate func import init
    inout internal let open operator private precedencegroup protocol public
    rethrows static struct subscript typealias var break case catch continue
    default defer do else fallthrough for guard if in repeat return throw
    switch where while as Any catch false is nil super self Self throws true
    try""".split()
)

IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def camel(name: str) -> str:
    """`arrow-square-out` -> `arrowSquareOut`."""
    head, *rest = name.split("-")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def escaped(identifier: str) -> str:
    return f"`{identifier}`" if identifier in SWIFT_KEYWORDS else identifier


def read_table() -> list[tuple[str, str]]:
    rows = []
    for line in TABLE.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        name, codepoint = line.split("\t")
        rows.append((name, codepoint.lower()))
    return rows


def main() -> int:
    rows = read_table()
    if not rows:
        print(f"no icons in {TABLE}", file=sys.stderr)
        return 1

    seen: dict[str, str] = {}
    for name, _ in rows:
        identifier = camel(name)
        if not IDENTIFIER.fullmatch(identifier):
            print(f"{name!r} -> {identifier!r} is not a Swift identifier", file=sys.stderr)
            return 1
        if identifier in seen:
            print(f"{name!r} and {seen[identifier]!r} both make {identifier!r}", file=sys.stderr)
            return 1
        seen[identifier] = name

    out = [
        "// Generated by tools/generate-icons.py — do not edit.",
        "//",
        f"// {len(rows)} names over {len({c for _, c in rows})} glyphs; the difference is",
        "// Phosphor's own aliases, kept so a name from its website or docs",
        "// always resolves.",
        "//",
        "// Computed rather than stored: an Icon is three fields and a",
        "// codepoint, so building one on demand costs less than the lazy-init",
        "// guard a `static let` would put behind every one of these.",
        "",
        "extension Icon {",
    ]
    for name, codepoint in rows:
        out.append(f"    /// `{name}`")
        out.append(
            f"    public static var {escaped(camel(name))}: Icon "
            f'{{ Icon(scalar: "\\u{{{codepoint}}}") }}'
        )
    out.append("}")
    out.append("")

    # Name lookup, for icons that arrive as data rather than as code —
    # a tab configuration, a server response, a theme file.
    out += [
        "// ── Lookup by name ────────────────────────────────────────────────────",
        "",
        "extension Icon {",
        "    /// Looks an icon up by its Phosphor name, e.g. `\"arrow-square-out\"`.",
        "    ///",
        "    /// For icons that arrive as data rather than as code. Returns nil for",
        "    /// an unknown name rather than rendering a blank, so a typo in a",
        "    /// config file is something you can actually notice.",
        "    ///",
        "    /// camelCase works too — `\"arrowSquareOut\"` finds the same icon — so",
        "    /// a name copied from either the website or this file resolves.",
        "    public init?(named name: String) {",
        "        guard let scalar = Icon.byName[name] ?? Icon.byName[Icon.kebab(name)] else {",
        "            return nil",
        "        }",
        "        self.init(scalar: scalar)",
        "    }",
        "",
        "    /// `arrowSquareOut` -> `arrow-square-out`, so both spellings hit the",
        "    /// same table rather than needing two of them.",
        "    ///",
        "    /// ASCII only, and not just because every icon name is: outside it,",
        "    /// lowercasing one character can produce two (`İ` becomes `i` plus a",
        "    /// combining dot), and `Character(_:)` traps on a multi-character",
        "    /// string. A lookup that can be handed arbitrary text must not be",
        "    /// able to crash on it.",
        "    static func kebab(_ name: String) -> String {",
        "        var out = \"\"",
        "        for character in name {",
        "            if character.isASCII, character.isUppercase {",
        "                out.append(\"-\")",
        "                out.append(Character(character.lowercased()))",
        "            } else {",
        "                out.append(character)",
        "            }",
        "        }",
        "        return out",
        "    }",
        "",
        "    /// Built once, on first use, and only if something actually looks an",
        "    /// icon up by name — the generated properties above don't touch it.",
        "    ///",
        "    /// No `nonisolated(unsafe)`: a `let` of an all-Sendable dictionary",
        "    /// needs no escape hatch, unlike the mutable registries elsewhere in",
        "    /// this module.",
        "    static let byName: [String: Unicode.Scalar] = [",
    ]
    for name, codepoint in rows:
        out.append(f'        "{name}": "\\u{{{codepoint}}}",')
    out.append("    ]")
    out.append("}")
    out.append("")

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} icons")
    return 0


if __name__ == "__main__":
    sys.exit(main())
