use std::path::{Path, PathBuf};

use crate::config::{Config, Orientation};

pub struct GradleProject {

    pub app_name: String,

    pub label: String,
    pub application_id: String,
    pub namespace: String,

    pub min_sdk: String,
    pub target_sdk: u32,
    pub version_name: String,

    pub version_code: u32,
    pub permissions: Vec<String>,
    pub orientation: Option<Orientation>,

    pub extra_application_attributes: Vec<(String, String)>,
}

impl GradleProject {

    pub fn resolve(
        project_root: &Path,
        app_name: &str,
        min_sdk: &str,
        config: &Config,
    ) -> GradleProject {
        let application_id = config
            .android_application_id()
            .map(str::to_string)

            .or_else(|| bundle_id_from_xtool(project_root))
            .unwrap_or_else(|| format!("com.swiftflow.{}", sanitise_id(app_name)));

        let namespace = config
            .android
            .namespace
            .clone()
            .unwrap_or_else(|| application_id.clone());

        GradleProject {
            app_name: app_name.to_string(),
            label: config
                .app
                .name
                .clone()
                .unwrap_or_else(|| app_name.to_string()),
            application_id,
            namespace,
            min_sdk: min_sdk.to_string(),
            target_sdk: config.android.target_sdk.unwrap_or(34),
            version_name: config
                .app
                .version
                .clone()
                .unwrap_or_else(|| "0.1".to_string()),
            version_code: config.app.build.unwrap_or(1),
            permissions: config.android_permissions(),
            orientation: config.app.orientation,
            extra_application_attributes: config
                .android
                .manifest
                .iter()
                .map(|(key, value)| (key.clone(), toml_scalar(value)))
                .collect(),
        }
    }

    pub fn write(&self, dir: &Path) -> Result<(), String> {
        for (path, contents) in self.files() {
            let full = dir.join(&path);
            if let Some(parent) = full.parent() {
                std::fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
            }
            std::fs::write(&full, contents).map_err(|e| format!("{}: {e}", full.display()))?;
        }
        Ok(())
    }

    pub fn files(&self) -> Vec<(PathBuf, String)> {
        vec![
            ("settings.gradle.kts".into(), self.settings()),
            ("build.gradle.kts".into(), ROOT_BUILD.to_string()),
            ("gradle.properties".into(), PROPERTIES.to_string()),
            ("app/build.gradle.kts".into(), self.app_build()),
            ("app/src/main/AndroidManifest.xml".into(), self.manifest()),
            (
                "app/src/main/res/values/themes.xml".into(),
                THEME.to_string(),
            ),
        ]
    }

    fn settings(&self) -> String {
        format!(
            r#"// Generated by `swiftflow`. Edits here are overwritten.
// To take ownership of the Android project, copy this directory to
// `android/` beside Package.swift — a project that has one is used
// verbatim and nothing is generated.

pluginManagement {{
    repositories {{
        google()
        mavenCentral()
        gradlePluginPortal()
    }}
}}

dependencyResolutionManagement {{
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {{
        google()
        mavenCentral()
    }}
}}

rootProject.name = "{}"
include(":app")
"#,
            self.app_name
        )
    }

    fn app_build(&self) -> String {
        format!(
            r#"// Generated by `swiftflow`. Edits here are overwritten.
//
// Packaging only. Nothing here compiles anything — the `.so` is built by
// `swiftflow` (Rust via cargo, Swift via a Swift SDK) and dropped into
// src/main/jniLibs before Gradle runs.
//
// There is still no `src/main/java` here — this project has no JVM
// *sources*. What it now has is one JVM *dependency*: the AGDK's
// GameActivity, which is why the manifest says `hasCode="true"`.
// Everything an Activity subclass would normally be written for is still
// reached through JNI reflection from Rust — see jni_metrics.rs.

plugins {{
    id("com.android.application")
}}

// Which ABI this APK is for. `swiftflow` passes -PswiftflowAbi to match
// whatever it just built; the default is the device case, so a bare
// `gradle assembleDebug` still does something sensible.
val swiftflowAbi: String = (project.findProperty("swiftflowAbi") as String?) ?: "arm64-v8a"

android {{
    namespace = "{namespace}"
    compileSdk = 34

    defaultConfig {{
        applicationId = "{application_id}"
        // Set by the Swift SDK, not by SwiftFlow. The API level is baked
        // into the Swift SDK's target triple
        // (aarch64-unknown-linux-android28), and a lower minSdk here would
        // let the APK install on a device the Swift runtime inside it
        // cannot run on. `swiftflow` derives this from
        // SWIFTFLOW_ANDROID_API, which also picks the triple.
        //
        // SwiftFlow's own floor is 24 — Choreographer's
        // AChoreographer_postFrameCallback. The two API calls above that
        // (getInsets at 30, getRoundedCorner at 31) already degrade to
        // sane values in jni_metrics.rs.
        minSdk = {min_sdk}
        targetSdk = {target_sdk}
        // From [app] build and [app] version. versionCode is monotonic —
        // a store or a device refuses an install that does not increase
        // it — which is why it is an integer of its own rather than
        // something derived from the semver string.
        versionCode = {version_code}
        versionName = "{version_name}"

        ndk {{
            // Must agree with the ABI that was actually built: filtering
            // to one keeps a stale .so for the other architecture out of
            // the APK, where it would be preferred on that device and fail
            // to load — but hardcoding arm64-v8a silently drops every
            // x86_64 build, producing an APK with no native code at all
            // and a crash at System.loadLibrary.
            abiFilters += setOf(swiftflowAbi)
        }}
    }}

    sourceSets {{
        getByName("main") {{
            jniLibs.srcDirs("src/main/jniLibs")
            assets.srcDirs("src/main/assets")
        }}
    }}

    packaging {{
        jniLibs {{
            // The Swift runtime and lib{app_name}.so are loaded with
            // System.loadLibrary, which needs real files on disk rather
            // than entries mapped straight out of the APK. Compressing
            // them would also make a cold start pay for inflating the
            // whole Swift runtime.
            useLegacyPackaging = true
        }}
    }}

    buildTypes {{
        getByName("debug") {{
            isMinifyEnabled = false
        }}
        getByName("release") {{
            // No shrinking. There is JVM code in the APK now — the AGDK's
            // GameActivity — but none of this project's own, and R8 has a
            // habit of stripping an Activity that is only ever named from
            // a manifest string.
            isMinifyEnabled = false
        }}
    }}
}}

dependencies {{
    // GameActivity, as an AAR. This is the entire Java dependency, and
    // the reason for it is soft-keyboard text: NativeActivity has no
    // route for it, GameActivity brings GameTextInput. Version 4.4.0 is
    // what android-activity 0.6 binds to — its Rust glue is compiled
    // against that release's C++ headers, so the two are one choice
    // rather than two.
    //
    // Prefab is deliberately NOT enabled. The AAR also ships the C++
    // glue as a prefab module, and letting Gradle compile *that* would
    // link a second copy of the same symbols the Rust crate already
    // built — android-activity's own README calls this out.
    implementation("androidx.games:games-activity:4.4.0")
}}
"#,
            application_id = self.application_id,
            namespace = self.namespace,
            min_sdk = self.min_sdk,
            target_sdk = self.target_sdk,
            version_code = self.version_code,
            version_name = self.version_name,
            app_name = self.app_name,
        )
    }

    fn manifest(&self) -> String {
        let permissions = self
            .permissions
            .iter()
            .map(|p| format!("    <uses-permission android:name=\"{p}\" />\n"))
            .collect::<String>();

        let mut application_attributes = vec![
            ("android:label".to_string(), self.label.clone()),

            ("android:hasCode".to_string(), "true".to_string()),
            ("android:allowBackup".to_string(), "false".to_string()),
        ];
        for (key, value) in &self.extra_application_attributes {
            let key = if key.starts_with("android:") {
                key.clone()
            } else {
                format!("android:{key}")
            };
            if let Some(slot) = application_attributes.iter_mut().find(|(k, _)| *k == key) {
                slot.1 = value.clone();
            } else {
                application_attributes.push((key, value.clone()));
            }
        }
        let application_attributes = application_attributes
            .iter()
            .map(|(k, v)| format!("\n        {k}=\"{}\"", escape_xml(v)))
            .collect::<String>();

        let orientation = self
            .orientation
            .map(|o| format!("\n            android:screenOrientation=\"{}\"", o.android()))
            .unwrap_or_default();

        format!(
            r#"<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by `swiftflow` from SwiftFlow.toml. Edits here are overwritten.

  There is no Java or Kotlin *source* in this project, but there is now
  JVM code in the APK: `com.google.androidgamesdk.GameActivity` comes
  from the AGDK as an AAR (androidx.games:games-activity), used
  unmodified.

  It replaced `android.app.NativeActivity` for one reason — soft-keyboard
  text. NativeActivity has no route for it at all: winit's Android
  backend never emits an IME event and discards the one android-activity
  raises, so a keyboard opened and nothing came back. GameActivity brings
  GameTextInput, whose buffer the Rust host reads directly (see
  rust/swiftflow_android/src/ime.rs).

  The entry point is unchanged in shape: android-activity's glue still
  exports it from lib{app_name}.so, and Rust's android_main still calls
  up into Swift. Window insets, the display's corner radius and its
  refresh rate still come from JNI reflection in
  rust/swiftflow_android/src/jni_metrics.rs, and the APK's assets are
  still unpacked through AAssetManager in src/assets.rs — none of that
  needed an Activity subclass before and none of it does now.

  `android.app.lib_name` names the library to load, without the `lib`
  prefix or the `.so` suffix. It matches the Swift target, since that is
  what SwiftPM names the dynamic-library product it emits.

  No `package` attribute: AGP 8 rejects it outright. The application ID
  comes from `namespace`/`applicationId` in app/build.gradle.kts instead.

  Permissions come from [capabilities]. INTERNET is always present:
  AsyncImage goes through URLSession, and without it the request is
  refused at the socket with no useful error — the image never arrives
  and the placeholder stays forever.
-->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

{permissions}
    <application{application_attributes}>

        <activity
            android:name="com.google.androidgamesdk.GameActivity"
            android:exported="true"
            android:launchMode="singleTask"{orientation}
            android:configChanges="orientation|screenSize|screenLayout|keyboardHidden|density|smallestScreenSize|uiMode"
            android:theme="@style/Theme.SwiftFlow">

            <meta-data
                android:name="android.app.lib_name"
                android:value="{app_name}" />

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"#,
            app_name = self.app_name,
        )
    }
}

fn toml_scalar(value: &toml::Value) -> String {
    match value {
        toml::Value::String(s) => s.clone(),
        other => other.to_string(),
    }
}

fn escape_xml(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

const ROOT_BUILD: &str = r#"// Generated by `swiftflow`. Edits here are overwritten.
//
// Root project. The Android Gradle plugin is declared here and applied in
// app/build.gradle.kts; `apply false` is what keeps it off the root.
plugins {
    id("com.android.application") version "8.5.2" apply false
}
"#;

const PROPERTIES: &str = r#"# Generated by `swiftflow`. Edits here are overwritten.
org.gradle.jvmargs=-Xmx2048m
# Required, not incidental. GameActivity extends AppCompatActivity and
# the theme parent is Theme.AppCompat — both AndroidX — so turning this
# off fails the resource merge. It was already true under NativeActivity,
# where nothing depended on it.
android.useAndroidX=true
android.nonTransitiveRClass=true
"#;

const THEME: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by `swiftflow`. Edits here are overwritten.

  Edge to edge, which is a requirement rather than a preference here.

  SwiftFlow draws its own navigation bar with a progressive blur that is
  meant to sit *under* the status bar, exactly as it does on iOS — that's
  what `SafeArea.top` is for, and the desktop host makes the same choice
  for the same reason (a transparent macOS titlebar with a full-size
  content view; see swiftflow_desktop/src/host.rs).

  The parent is an AppCompat theme, and that is a requirement rather
  than a preference: GameActivity extends AppCompatActivity, which throws
  "You need to use a Theme.AppCompat theme (or descendant) with this
  activity" at startup against a platform theme. It was
  @android:style/Theme.DeviceDefault.NoActionBar under NativeActivity,
  which had no such constraint.

  Without the edge-to-edge items below, the window is laid out inside the
  system bars: the surface would start below the status bar, the insets would be
  reported as zero, and the blur band would have nothing to sit under. The
  bar would look correct in isolation and wrong against every iOS
  screenshot.

  `windowLayoutInDisplayCutoutMode` is API 28 and `enforceNavigationBarContrast`
  is API 29; an attribute a device doesn't know is ignored rather than an
  error, which is why there are no `values-vNN` variants of this file.
-->
<resources>
    <style name="Theme.SwiftFlow" parent="Theme.AppCompat.NoActionBar">
        <!-- Draw behind the bars rather than being laid out inside them. -->
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:navigationBarColor">@android:color/transparent</item>
        <!-- Extend into the notch/cutout too, so a full-bleed background
             reaches the top of the display. jni_metrics.rs folds the
             cutout into the safe area it reports, so content still keeps
             clear of it. -->
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
        <!-- The system otherwise paints a scrim behind the gesture bar,
             which would sit on top of whatever SwiftFlow drew there. -->
        <item name="android:enforceNavigationBarContrast">false</item>
        <item name="android:enforceStatusBarContrast">false</item>
        <item name="android:windowBackground">@android:color/black</item>
    </style>
</resources>
"#;

fn bundle_id_from_xtool(project_root: &Path) -> Option<String> {
    let text = std::fs::read_to_string(project_root.join("xtool.yml")).ok()?;
    for line in text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("bundleID:") {
            let value = rest.trim().trim_matches(['"', '\'']);
            if !value.is_empty() {
                return Some(value.to_string());
            }
        }
    }
    None
}

fn sanitise_id(name: &str) -> String {
    let lowered: String = name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .collect::<String>()
        .to_ascii_lowercase();

    if lowered.is_empty() {
        "app".to_string()
    } else if lowered.starts_with(|c: char| c.is_ascii_digit()) {
        format!("a{lowered}")
    } else {
        lowered
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("sf-gradle-{tag}-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn config(text: &str) -> Config {
        toml::from_str(text).expect("test config should parse")
    }

    fn resolve(dir: &Path, name: &str, text: &str) -> GradleProject {
        GradleProject::resolve(dir, name, "28", &config(text))
    }

    fn file<'a>(project: &'a [(PathBuf, String)], ends_with: &str) -> &'a str {
        &project
            .iter()
            .find(|(p, _)| p.to_string_lossy().ends_with(ends_with))
            .unwrap_or_else(|| panic!("no {ends_with} in the generated project"))
            .1
    }

    #[test]
    fn canonical_values_reach_both_files() {
        let dir = tmp("canonical");
        let project = resolve(
            &dir,
            "Reader",
            r#"
[app]
id = "com.acme.reader"
name = "Acme Reader"
version = "2.1.0"
build = 47
"#,
        );
        let files = project.files();
        let gradle = file(&files, "app/build.gradle.kts");
        assert!(gradle.contains(r#"applicationId = "com.acme.reader""#));
        assert!(gradle.contains(r#"namespace = "com.acme.reader""#));
        assert!(gradle.contains("versionCode = 47"));
        assert!(gradle.contains(r#"versionName = "2.1.0""#));

        let manifest = file(&files, "AndroidManifest.xml");
        assert!(manifest.contains(r#"android:label="Acme Reader""#));

        assert!(manifest.contains(r#"android:value="Reader""#));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn typed_beats_canonical() {
        let dir = tmp("typed");
        let project = resolve(
            &dir,
            "Reader",
            r#"
[app]
id = "com.acme.reader"
[android]
application_id = "com.acme.reader.pro"
target_sdk = 33
"#,
        );
        let files = project.files();
        let gradle = file(&files, "app/build.gradle.kts");
        assert!(gradle.contains(r#"applicationId = "com.acme.reader.pro""#));
        assert!(gradle.contains("targetSdk = 33"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn raw_beats_everything() {

        let dir = tmp("raw");
        let project = resolve(
            &dir,
            "Reader",
            r##"
[app]
name = "Derived Name"
[android.manifest]
"android:label" = "Raw Name"
"android:hardwareAccelerated" = true
"##,
        );
        let manifest = &project.files();
        let manifest = file(manifest, "AndroidManifest.xml");
        assert!(manifest.contains(r#"android:label="Raw Name""#));
        assert!(!manifest.contains("Derived Name"));

        assert!(manifest.contains(r#"android:hardwareAccelerated="true""#));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn capabilities_become_permissions() {
        let dir = tmp("caps");
        let project = resolve(
            &dir,
            "Reader",
            r#"
[capabilities.camera]
reason = "Scan pages."
"#,
        );
        let files = project.files();
        let manifest = file(&files, "AndroidManifest.xml");
        assert!(manifest.contains("android.permission.CAMERA"));

        assert!(manifest.contains("android.permission.INTERNET"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn orientation_reaches_the_activity() {
        let dir = tmp("orientation");
        let project = resolve(&dir, "Reader", "[app]\norientation = \"portrait\"\n");
        let files = project.files();
        assert!(file(&files, "AndroidManifest.xml").contains(r#"android:screenOrientation="portrait""#));

        let project = resolve(&dir, "Reader", "");
        let files = project.files();
        assert!(!file(&files, "AndroidManifest.xml").contains("screenOrientation"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn the_bundle_id_falls_back_to_xtool_then_to_the_name() {
        let dir = tmp("fallback");
        std::fs::write(dir.join("xtool.yml"), "version: 1\nbundleID: com.acme.reader\n").unwrap();
        assert_eq!(resolve(&dir, "Reader", "").application_id, "com.acme.reader");

        std::fs::remove_file(dir.join("xtool.yml")).unwrap();
        assert_eq!(
            resolve(&dir, "My-Cool App", "").application_id,
            "com.swiftflow.mycoolapp"
        );

        std::fs::write(dir.join("xtool.yml"), "bundleID: com.old.id\n").unwrap();
        assert_eq!(
            resolve(&dir, "Reader", "[app]\nid = \"com.new.id\"\n").application_id,
            "com.new.id"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn a_package_segment_never_starts_with_a_digit() {
        assert_eq!(sanitise_id("2048"), "a2048");
        assert_eq!(sanitise_id("---"), "app");
    }

    #[test]
    fn attribute_values_are_escaped() {
        let dir = tmp("escape");
        let project = resolve(&dir, "Reader", "[app]\nname = \"Tom & Jerry\"\n");
        let files = project.files();
        let manifest = file(&files, "AndroidManifest.xml");
        assert!(manifest.contains("Tom &amp; Jerry"), "unescaped XML would not parse");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn writing_twice_leaves_the_build_output_alone() {

        let dir = tmp("write");
        let project = resolve(&dir, "Reader", "");
        project.write(&dir).unwrap();

        let jni = dir.join("app/src/main/jniLibs/arm64-v8a");
        std::fs::create_dir_all(&jni).unwrap();
        std::fs::write(jni.join("libReader.so"), b"not really").unwrap();

        project.write(&dir).unwrap();
        assert!(jni.join("libReader.so").is_file(), "the .so was discarded");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn the_four_halves_of_the_game_activity_swap_agree() {
        let dir = tmp("game-activity");
        let project = resolve(&dir, "Demo", "").files();

        let manifest = file(&project, "AndroidManifest.xml");
        assert!(
            manifest.contains("com.google.androidgamesdk.GameActivity"),
            "the activity itself"
        );

        assert!(
            !manifest.contains(r#"android:name="android.app.NativeActivity""#),
            "NativeActivity must be replaced, not joined"
        );

        assert!(
            manifest.contains(r#"android:hasCode="true""#),
            "hasCode stopped being false the moment an AAR came in"
        );

        let theme = file(&project, "themes.xml");
        assert!(
            theme.contains(r#"parent="Theme.AppCompat"#),
            "an AppCompat parent is required, not preferred"
        );

        let gradle = file(&project, "app/build.gradle.kts");
        assert!(
            gradle.contains("androidx.games:games-activity:4.4.0"),
            "the AAR the other three depend on"
        );
    }

    #[test]
    fn prefab_stays_off() {
        let dir = tmp("prefab");
        let project = resolve(&dir, "Demo", "").files();
        let gradle = file(&project, "app/build.gradle.kts");
        assert!(
            !gradle.contains("prefab = true"),
            "android-activity builds this glue itself"
        );
    }

}
