use std::path::{Path, PathBuf};

use crate::config::Config;

pub const FILE_NAME: &str = "xtool.yml";

const BANNER: &str = "# Generated by `swiftflow` from SwiftFlow.toml. Edits here are overwritten.";

/// The `xtool.yml` an iOS build needs, from the app's own config.
///
/// Everything in it is already in `SwiftFlow.toml`, so it is derived
/// rather than authored — one file describes the app on every platform,
/// the same way the Gradle project is generated from it on Android.
pub fn contents(app_name: &str, config: &Config) -> String {
    let bundle_id = config
        .app
        .id
        .clone()
        .unwrap_or_else(|| format!("com.swiftflow.{}", sanitise(app_name)));
    format!("{BANNER}\nversion: 1\nbundleID: {bundle_id}\n")
}

/// Whether this file is ours to overwrite.
///
/// An app that wants to hand-write one deletes the banner, and from then
/// on the build leaves it alone — the same escape hatch a real `android/`
/// directory is on the other platform.
pub fn is_generated(text: &str) -> bool {
    text.lines().next().is_some_and(|line| line.trim() == BANNER)
}

/// Writes it beside `Package.swift` — where xtool reads it from — and
/// takes it away again when the returned value is dropped.
///
/// Scoped rather than left on disk because it is derived: it exists for
/// the length of one build and nothing outside that build should see it.
/// Dropping rather than deleting at the end of the happy path is what
/// makes a failed build clean up after itself too.
pub fn scoped(
    project_root: &Path,
    app_name: &str,
    config: &Config,
) -> Result<Generated, String> {
    let path = project_root.join(FILE_NAME);
    if std::fs::read_to_string(&path).is_ok_and(|text| !is_generated(&text)) {
        return Ok(Generated { path, ours: false });
    }
    std::fs::write(&path, contents(app_name, config))
        .map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(Generated { path, ours: true })
}

pub struct Generated {
    path: PathBuf,
    /// False for a file the app wrote itself, which is never touched.
    ours: bool,
}

impl Drop for Generated {
    fn drop(&mut self) {
        if self.ours {
            let _ = std::fs::remove_file(&self.path);
        }
    }
}

fn sanitise(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .collect::<String>()
        .to_lowercase();
    if cleaned.is_empty() {
        "app".to_string()
    } else {
        cleaned
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config(id: Option<&str>) -> Config {
        let mut c = Config::default();
        c.app.id = id.map(str::to_string);
        c
    }

    #[test]
    fn the_bundle_id_comes_from_the_app_config() {
        assert!(contents("Reader", &config(Some("com.acme.reader")))
            .contains("bundleID: com.acme.reader"));
    }

    #[test]
    fn an_app_without_an_id_gets_one_from_its_name() {
        assert!(contents("My App", &config(None)).contains("bundleID: com.swiftflow.myapp"));
    }

    #[test]
    fn a_hand_written_file_is_left_alone() {
        assert!(is_generated(&contents("Reader", &config(None))));
        assert!(!is_generated("version: 1\nbundleID: com.acme.reader\n"));
    }

    fn temp(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("sf-xtool-{tag}-{}", std::process::id()));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn it_exists_for_the_build_and_not_after() {
        let dir = temp("scope");
        let path = dir.join(FILE_NAME);
        {
            let _guard = scoped(&dir, "Reader", &config(Some("com.acme.reader"))).unwrap();
            let text = std::fs::read_to_string(&path).unwrap();
            assert!(text.contains("bundleID: com.acme.reader"), "{text}");
        }
        assert!(!path.exists(), "the generated file outlived the build");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn a_hand_written_file_is_neither_overwritten_nor_removed() {
        let dir = temp("mine");
        let path = dir.join(FILE_NAME);
        let mine = "version: 1\nbundleID: com.mine.app\n";
        std::fs::write(&path, mine).unwrap();
        {
            let _guard = scoped(&dir, "Reader", &config(Some("com.acme.reader"))).unwrap();
            assert_eq!(std::fs::read_to_string(&path).unwrap(), mine);
        }
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            mine,
            "the app's own file was deleted"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn a_file_left_by_an_interrupted_build_is_reclaimed() {
        // Drop doesn't run if the process is killed, so the next build has
        // to recognise its own leftover by the banner and clear it.
        let dir = temp("stale");
        let path = dir.join(FILE_NAME);
        std::fs::write(&path, contents("Reader", &config(Some("com.old.id")))).unwrap();
        {
            let _guard = scoped(&dir, "Reader", &config(Some("com.new.id"))).unwrap();
            let text = std::fs::read_to_string(&path).unwrap();
            assert!(text.contains("bundleID: com.new.id"), "{text}");
        }
        assert!(!path.exists());
        std::fs::remove_dir_all(&dir).ok();
    }
}
